DROP DATABASE IF EXISTS quiz_app;
CREATE DATABASE quiz_app CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE quiz_app;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE quizzes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  answer_index INT NOT NULL,
  tag VARCHAR(100),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE choices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  quiz_id INT NOT NULL,
  choice_text VARCHAR(255) NOT NULL,
  index_number INT NOT NULL,
  FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE
);

CREATE TABLE progress (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  choice_id INT NOT NULL,
  answered_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (choice_id) REFERENCES choices(id) ON DELETE CASCADE
);

INSERT INTO quizzes (id, title, content, answer_index, tag) VALUES
(1, "colorプロパティの効果", "次のCSSが意味することとして正しいのは？\n<pre><code class=\"language-css\">p {\ncolor: red;\n}</code></pre>", 1, "CSS"),
(2, "idセレクタの指定", "次のCSSが適用される要素はどれ？\n<pre><code class=\"language-css\">#main {\nfont-size: 20px;\n}</code></pre>", 0, "CSS"),
(3, "複数クラスの指定", "次のCSSが適用されるのは？\n<pre><code class=\"language-css\">.box.red {\nbackground-color: red;\n}</code></pre>", 0, "CSS"),
(4, "パーセント指定の基準", "次のCSSで「50%」の基準となるのは何？\n<pre><code class=\"language-css\">.box {\nwidth: 50%;\n}</code></pre>", 0, "CSS"),
(5, "マージンの略記", "次のCSSの効果は？\n<pre><code class=\"language-css\">margin: 10px 20px;</code></pre>", 0, "CSS"),
(6, "継承されるプロパティ", "親要素から自動的に継承されるのはどれ？", 0, "CSS"),
(7, "セレクタの強さ", "次のうち、より強いセレクタは？", 1, "CSS"),
(8, "display: noneの効果", "次のCSSが意味するのは？\n<pre><code class=\"language-css\">display: none;</code></pre>", 1, "CSS"),
(9, ":hoverのタイミング", "次のスタイルはいつ適用される？\n<pre><code class=\"language-css\">a:hover {\ncolor: blue;\n}</code></pre>", 1, "CSS"),
(10, "paddingの位置", "「padding」が指すのはどの部分？", 1, "CSS"),
(11, "HTML格付けチェック 1", "次のフォームは何が間違っていますか？<pre><code class=\"language-html\">&lt;form&gt;\n  &lt;input text=&quot;name&quot;&gt;\n  &lt;input type=&quot;submit&quot; 送信&gt;\n&lt;/form&gt;</code></pre>", 1, "HTML"),
(12, "HTML格付けチェック 2", "意味的に正しいのはどちらですか？<pre><code class=\"language-html\">&lt;!-- A --&gt;\n&lt;div id=&quot;main&quot;&gt;内容&lt;/div&gt;\n\n&lt;!-- B --&gt;\n&lt;main&gt;内容&lt;/main&gt;</code></pre>", 1, "HTML"),
(13, "HTML格付けチェック 3", "関連リンクや広告のエリアを囲むのに最も適切なタグは？", 1, "HTML"),
(14, "HTML格付けチェック 4", "以下の見出し構造は正しいですか？<pre><code class=\"language-html\">&lt;h1&gt;概要&lt;/h1&gt;\n&lt;h3&gt;社名&lt;/h3&gt;\n&lt;h2&gt;所在地&lt;/h2&gt;</code></pre>", 1, "HTML"),
(15, "HTML格付けチェック 5", "次のHTMLの表示結果は？<pre><code class=\"language-html\">&lt;p&gt;1 &amp;lt; 2 and 3 &amp;gt; 2&lt;/p&gt;</code></pre>", 0, "HTML"),
(16, "HTML格付けチェック 6", "次のタグに閉じタグは必要ですか？<pre><code class=\"language-html\">&lt;img src=&quot;logo.png&quot;&gt;\n&lt;br&gt;\n&lt;hr&gt;</code></pre>", 3, "HTML"),
(17, "HTML格付けチェック 7", "&lt;h1&gt; と &lt;h6&gt; の違いは？", 1, "HTML"),
(18, "HTML格付けチェック 8", "次のリンクにおいて、target=&quot;_blank&quot; の意味は？<pre><code class=\"language-html\">&lt;a href=&quot;https://example.com&quot; target=&quot;_blank&quot;&gt;こちら&lt;/a&gt;</code></pre>", 1, "HTML"),
(19, "HTML格付けチェック 9", "テキスト「送信」と表示される最適なボタンタグは？", 1, "HTML"),
(20, "HTML格付けチェック 10", "&lt;div&gt; と &lt;span&gt; の違いは？", 1, "HTML"),
(21, "第1問", "次のうち、プリミティブ型に該当しないものはどれか", 2, "JavaScript"),
(22, "第2問", "以下のJavaScriptコードを実行した結果として正しいものは？\n<pre><code class=\"language-js\">console.log(typeof NaN);</code></pre>", 3, "JavaScript"),
(23, "第3問", "以下のJavaScriptコードを実行した結果として正しいものは？\n<pre><code class=\"language-js\">const nums = [1, 2, 3];\nnums.push(4);\nconsole.log(nums);</code></pre>", 1, "JavaScript"),
(24, "第4問", "次のうちテンプレートリテラルの構文として正しいものはどれか", 2, "JavaScript"),
(25, "第5問", "次の中で Falsy な値として正しいものはどれか（複数選択可）", 4, "JavaScript"),
(26, "第6問", "以下のJavaScriptコードを実行した結果として正しいものは？\n<pre><code class=\"language-js\">const arr = [1, 2, 3, 4, 5];\narr.splice(2, 2);\nconsole.log(arr);</code></pre>", 1, "JavaScript"),
(27, "第7問", "以下のJavaScriptコードを実行した結果として正しいものは？\n<pre><code class=\"language-js\">console.log([[1, 2], [3, 4]][1][0]);</code></pre>", 1, "JavaScript"),
(28, "第8問", "以下のJavaScriptコードを実行した結果として正しいものは？\n<pre><code class=\"language-js\">const obj = { a: 1 };\nobj.b = 2;\nconsole.log(obj);</code></pre>", 1, "JavaScript"),
(29, "第9問", "以下のJavaScriptコードは何回 \"Hello\" を表示するか？\n<pre><code class=\"language-js\">for (let i = 0; i < 3; i++) {\n  console.log(\"Hello\");\n}</code></pre>", 2, "JavaScript"),
(30, "第10問", "以下のJavaScriptコードを実行した結果として正しいものは？\n<pre><code class=\"language-js\">function test() {\n  let x = 10;\n}\ntest();\nconsole.log(x);</code></pre>", 2, "JavaScript");

INSERT INTO choices (quiz_id, choice_text, index_number) VALUES
-- CSS (1〜10)
(1, '背景色が赤になる', 0),
(1, '文字色が赤になる', 1),
(2, 'id="main" の要素', 0),
(2, 'class="main" の要素', 1),
(3, 'class="box red" の要素', 0),
(3, 'class="red" の要素', 1),
(3, 'どちらも適用される', 2),
(4, '親要素の幅', 0),
(4, '自分自身のサイズ', 1),
(5, '上下10px、左右20pxの余白', 0),
(5, '上下20px、左右10pxの余白', 1),
(6, 'color', 0),
(6, 'width', 1),
(7, '.box', 0),
(7, '#box', 1),
(8, '要素は非表示だが場所は空けて残る', 0),
(8, '要素も完全に消え、場所も取らない', 1),
(9, '常に適用される', 0),
(9, 'マウスを乗せたときに適用される', 1),
(10, '境界線の外側', 0),
(10, '内容と境界線の間', 1),

-- HTML (11〜20)
(11, 'テキストが足りない', 0),
(11, '属性名・属性値が正しくない', 1),
(12, 'A', 0),
(12, 'B', 1),
(13, '<section>', 0),
(13, '<aside>', 1),
(14, '正しい', 0),
(14, '正しくない', 1),
(15, '1 < 2 and 3 > 2', 0),
(15, '1 &lt; 2 and 3 &gt; 2', 1),
(16, 'imgタグに閉じタグが必要', 0),
(16, 'brタグに閉じタグが必要', 1),
(16, 'hrタグに閉じタグが必要', 2),
(16, '全て閉じタグは不要', 3),
(17, '見た目だけの違い', 0),
(17, '文書構造の階層を示す', 1),
(18, 'リンクをモーダルで開く', 0),
(18, '新しいタブで開く', 1),
(19, '<input type="button" value="送信">', 0),
(19, '<button>送信</button>', 1),
(20, 'どちらも同じ使い方', 0),
(20, 'div はブロック、 span はインライン', 1),

-- JavaScript (21〜30)
(21, 'Number', 0),
(21, 'Boolean', 1),
(21, 'Object', 2),
(21, 'String', 3),
(22, '"NaN"', 0),
(22, '"undefined"', 1),
(22, '"object"', 2),
(22, '"number"', 3),
(23, 'エラーが出る', 0),
(23, '[1, 2, 3, 4]', 1),
(23, 'undefined', 2),
(23, '"1,2,3,4"', 3),
(24, '\'Hello, ${name}\'', 0),
(24, '"Hello, ${name}"', 1),
(24, 'Hello, ${name}', 2),
(24, 'Hello, $name', 3),
(25, '0', 0),
(25, '[]', 1),
(25, '""', 2),
(25, 'null', 3),
(25, '※正解は A, C, D の複数選択', 4),
(26, '[1, 2, 3, 4, 5]', 0),
(26, '[1, 2, 5]', 1),
(26, '[3, 4]', 2),
(26, '[1, 2]', 3),
(27, '1', 0),
(27, '3', 1),
(27, '4', 2),
(27, 'undefined', 3),
(28, '{a: 1}', 0),
(28, '{a: 1, b: 2}', 1),
(28, 'エラーが出る', 2),
(28, 'undefined', 3),
(29, '1回', 0),
(29, '2回', 1),
(29, '3回', 2),
(29, '無限ループになる', 3),
(30, '10', 0),
(30, 'undefined', 1),
(30, 'エラーが出る', 2),
(30, 'null', 3);
